# Discord にゃんこエージェント ボット - Cloud Build 設定
# Google Cloud Build でのコンテナビルドとデプロイを自動化

steps:
  # Docker イメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'config/docker/Dockerfile.single',
      '-t', 'gcr.io/$PROJECT_ID/discord-nyanco-agent:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/discord-nyanco-agent:latest',
      '.'
    ]
    dir: 'bot'

  # Docker イメージを Container Registry にプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/discord-nyanco-agent:$BUILD_ID']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/discord-nyanco-agent:latest']

  # Cloud Run にデプロイ
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'discord-nyanco-agent',
      '--image', 'gcr.io/$PROJECT_ID/discord-nyanco-agent:$BUILD_ID',
      '--region', 'asia-northeast1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '1Gi',
      '--cpu', '1',
      '--concurrency', '1',
      '--max-instances', '1',
      '--min-instances', '1',
      '--port', '8080',
      '--set-env-vars', 'PYTHONUNBUFFERED=1,PROJECT_ID=$PROJECT_ID,GOOGLE_CLOUD_PROJECT=$PROJECT_ID',
      '--update-secrets', 'DISCORD_BOT_TOKEN=discord-bot-token:latest,FIREBASE_SERVICE_ACCOUNT=firebase-service-account:latest',
      '--timeout', '3600'
    ]

# ビルド設定
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# タイムアウト設定（20分）
timeout: '1200s'

# Secret Manager からの環境変数設定
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/discord-bot-token/versions/latest
      env: 'DISCORD_BOT_TOKEN'
    - versionName: projects/$PROJECT_ID/secrets/firebase-service-account/versions/latest
      env: 'FIREBASE_SERVICE_ACCOUNT'