version: '3.8'

services:
  # みやにゃんボット
  miya-bot:
    image: gcr.io/nyanco-bot/discord-nyanco-agent-miya:latest
    container_name: miya-nyanco-bot
    environment:
      # ボットキャラクター指定
      - BOT_CHARACTER=miya
      
      # Discord トークン（GCP Secret Managerから取得）
      - DISCORD_BOT_TOKEN_MIYA=${DISCORD_BOT_TOKEN_MIYA}
      
      # Firebase 設定（GCP Secret Managerから取得）
      - FIREBASE_SERVICE_ACCOUNT=${FIREBASE_SERVICE_ACCOUNT:-}
      
      # Gemini API（GCP Secret Managerから取得）
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      
      # GCP固有設定
      - GOOGLE_CLOUD_PROJECT=nyanco-bot
      - PORT=8080
      
      # ログ設定
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
    ports:
      - "8081:8080"
    restart: unless-stopped
    logging:
      driver: "gcplogs"
      options:
        gcp-project: "nyanco-bot"
        gcp-log-cmd: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - nyanco-network
    # GCP Compute Engine用のリソース制限
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # イヴにゃんボット
  eve-bot:
    image: gcr.io/nyanco-bot/discord-nyanco-agent-eve:latest
    container_name: eve-nyanco-bot
    environment:
      # ボットキャラクター指定
      - BOT_CHARACTER=eve
      
      # Discord トークン（GCP Secret Managerから取得）
      - DISCORD_BOT_TOKEN_EVE=${DISCORD_BOT_TOKEN_EVE}
      
      # Firebase 設定（GCP Secret Managerから取得）
      - FIREBASE_SERVICE_ACCOUNT=${FIREBASE_SERVICE_ACCOUNT:-}
      
      # Gemini API（GCP Secret Managerから取得）
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      
      # GCP固有設定
      - GOOGLE_CLOUD_PROJECT=nyanco-bot
      - PORT=8080
      
      # ログ設定
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
    ports:
      - "8082:8080"
    restart: unless-stopped
    logging:
      driver: "gcplogs"
      options:
        gcp-project: "nyanco-bot"
        gcp-log-cmd: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - nyanco-network
    # GCP Compute Engine用のリソース制限
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # ロードバランサー/リバースプロキシ（オプション）
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl-certs:/etc/nginx/ssl:ro
    depends_on:
      - miya-bot
      - eve-bot
    restart: unless-stopped
    networks:
      - nyanco-network
    # ロードバランサー用リソース制限
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'

networks:
  nyanco-network:
    driver: bridge

# GCP固有のボリューム設定
volumes:
  bot-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/nyanco-bot/logs
  
  ssl-certs:
    driver: local
    driver_opts:
      type: none  
      o: bind
      device: /opt/nyanco-bot/ssl