name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    branches: [ main ]
    types: [ completed ]

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: 'asia-northeast1'
  NODE_VERSION: '20'

jobs:
  # デプロイ前のテスト確認
  verify-tests:
    name: Verify Tests Passed
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'push'
    
    steps:
    - name: Verify CI passed
      run: echo "All tests passed, proceeding with deployment"

  # Firebase Functions & Hosting デプロイ
  deploy-firebase:
    name: Deploy Firebase
    runs-on: ubuntu-latest
    needs: verify-tests
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Firebase Functions dependencies
      run: |
        cd functions
        npm ci
        
    - name: Build TypeScript project
      run: npm run build
      
    - name: Build Firebase Functions
      run: |
        cd functions
        npm run build
        
    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'
        channelId: live



  # ヘルスチェック
  health-check:
    name: Health Check
    runs-on: ubuntu-latest
    needs: [deploy-firebase]
    
    steps:
    - name: Wait for deployment
      run: sleep 60
      
    - name: Check Firebase Hosting
      run: |
        curl -f https://${{ secrets.FIREBASE_PROJECT_ID }}.web.app/health || \
        curl -f https://${{ secrets.FIREBASE_PROJECT_ID }}.firebaseapp.com/health || \
        echo "Firebase hosting health check failed"

  # Slack通知
  notify-deployment:
    name: Notify Deployment
    runs-on: ubuntu-latest
    needs: [deploy-firebase, health-check]
    if: always()
    
    steps:
    - name: Notify Success
      if: needs.deploy-firebase.result == 'success'
      uses: 8398a7/action-slack@v3
      with:
        status: success
        text: |
          🎉 Deployment Successful!
          • Firebase: Deployed
          • Commit: ${{ github.sha }}
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        
    - name: Notify Failure
      if: needs.deploy-firebase.result == 'failure'
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        text: |
          ❌ Deployment Failed!
          • Firebase: ${{ needs.deploy-firebase.result }}
          • Commit: ${{ github.sha }}
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}